### ISSUE TITLE
Примечания к bookstore

### ISSUE THREAD

**Issue by aroditelev** [Fallet666/bookstore#1]
- Если мы не используем конструктор копирования по умолчанию, то лучше явно это указать, иначе без инициализации данных добавление в БД не имеет никакого смысла
- explicit имеет смысл использовать во всех трех классах
- Хранить массив копий на стеке  Books слишком накладно, лучше использовать кучу и например shared_ptr

**Comment by Fallet666** [comment]
исправил, большое спасибо за обратную связь!
